### ISSUE TITLE
Extension example not working

### ISSUE THREAD

**Issue by cu** [frostming/marko#108]
Hello!

I am trying to get the extension example working as it is written in the docs but I am not having any luck. The code looks like this (with a minor modification to prevent a class naming collision):

```python
from marko import Markdown, inline

class GitHubWikiElement(inline.InlineElement):
    pattern = r'\[\[ *(.+?) *| *(.+?) *\]\]'
    parse_childern = True
    
    def __init__(self, match):
        self.target = match.group(2)

class WikiRendererMixin:
    def render_wiki_link(self, element):
        return '<a href="{}">{}</a>'.format(
            self.escape_url(element.target), self.render_children(element)
        )

class GitHubWiki:
    elements = [GitHubWikiElement]
    renderer_mixins = [WikiRendererMixin]

md = Markdown()
md.use(GitHubWiki)

print(md("foo *bar*"))
print(md("Example [[wiki link]] and some text"))
```

This is the output:

```
<p>foo <em>bar</em></p>

Traceback (most recent call last):
  File "/home/eil/git/github/cu/python-markdown-renderers/marko/marko_wiki_link_test.py", line 24, in <module>
    print(md("Example [[wiki link]] and some text"))
  File "/home/eil/.cache/pypoetry/virtualenvs/marko-env-7g-_3URi-py3.9/lib/python3.9/site-packages/marko/__init__.py", line 106, in __call__
    return self.convert(text)
  File "/home/eil/.cache/pypoetry/virtualenvs/marko-env-7g-_3URi-py3.9/lib/python3.9/site-packages/marko/__init__.py", line 103, in convert
    return self.render(self.parse(text))
  File "/home/eil/.cache/pypoetry/virtualenvs/marko-env-7g-_3URi-py3.9/lib/python3.9/site-packages/marko/__init__.py", line 123, in render
    return r.render(parsed)
  File "/home/eil/.cache/pypoetry/virtualenvs/marko-env-7g-_3URi-py3.9/lib/python3.9/site-packages/marko/renderer.py", line 65, in render
    return self.render_children(element)
  File "/home/eil/.cache/pypoetry/virtualenvs/marko-env-7g-_3URi-py3.9/lib/python3.9/site-packages/marko/renderer.py", line 79, in render_children
    rendered = [self.render(child) for child in element.children]  # type: ignore
  File "/home/eil/.cache/pypoetry/virtualenvs/marko-env-7g-_3URi-py3.9/lib/python3.9/site-packages/marko/renderer.py", line 79, in <listcomp>
    rendered = [self.render(child) for child in element.children]  # type: ignore
  File "/home/eil/.cache/pypoetry/virtualenvs/marko-env-7g-_3URi-py3.9/lib/python3.9/site-packages/marko/renderer.py", line 64, in render
    return render_func(element)
  File "/home/eil/.cache/pypoetry/virtualenvs/marko-env-7g-_3URi-py3.9/lib/python3.9/site-packages/marko/html_renderer.py", line 14, in render_paragraph
    children = self.render_children(element)
  File "/home/eil/.cache/pypoetry/virtualenvs/marko-env-7g-_3URi-py3.9/lib/python3.9/site-packages/marko/renderer.py", line 79, in render_children
    rendered = [self.render(child) for child in element.children]  # type: ignore
  File "/home/eil/.cache/pypoetry/virtualenvs/marko-env-7g-_3URi-py3.9/lib/python3.9/site-packages/marko/renderer.py", line 79, in <listcomp>
    rendered = [self.render(child) for child in element.children]  # type: ignore
  File "/home/eil/.cache/pypoetry/virtualenvs/marko-env-7g-_3URi-py3.9/lib/python3.9/site-packages/marko/renderer.py", line 65, in render
    return self.render_children(element)
  File "/home/eil/.cache/pypoetry/virtualenvs/marko-env-7g-_3URi-py3.9/lib/python3.9/site-packages/marko/renderer.py", line 79, in render_children
    rendered = [self.render(child) for child in element.children]  # type: ignore
AttributeError: 'GitHubWikiElement' object has no attribute 'children'
```
Greatly appreciate any advice.

**Comment by frostming** [comment]
There are several mistakes in your code:
1. Typo: `parse_childern` -> `parse_children`. This is the main cause of the exception.
2. the regex pattern should be `pattern = r'\[\[ *(.+?) *\| *(.+?) *\]\]'`, where `|` should be escaped.(The documentation is also wrong here, will fix it soon)
3. The render method name is derived from the element class, converting the CamelCase to snake_case, so it should be `render_git_hub_wiki_element`.
4. According to the regex pattern, there must be a `|` in the link, so `[[wiki|link]]` should work.

**Comment by cu** [comment]
Well that's embarrassing. Guess I shouldn't try coding while tired. Thank you!
