### ISSUE TITLE
Render using MarkdownRenderer

### ISSUE THREAD

**Issue by multipleofzero** [frostming/marko#150]
I am trying to use the `MarkdownRenderer` to output a parsed `Document` as markdown. Unfortunately I am unable to figure out how to do this. Either I get the document rendered by the (default) HTMLRenderer or I get an error.

Here is what I am trying (I have also tried many variations, which all failed):

```python
import marko
from marko.md_renderer import MarkdownRenderer

# first, load an existing document (this is working fine)
md_doc = marko.parse(md_text)  # md_doc is <marko.block.Document object at 0x...>
<do some work>
md_writer = marko.Markdown(renderer=MarkdownRenderer)
md_source = md_writer.render(md_doc)
```

However, the last line throws an error:

```python
Traceback (most recent call last):
  File "/Users/.../update.py", line 256, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/.../update.py", line 48, in main
    _update_document(page_id=test_page_id, doc=md, api_token=api_token)
  File "/Users/.../update.py", line 90, in _update_document
    md_source = md_writer.render(md_doc),
            ^^^^^^^^^^^^^^^
  File "/Users/.../lib/python3.11/site-packages/marko/__init__.py", line 129, in render
    self.renderer.root_node = parsed
    ^^^^^^^^^^^^^
AttributeError: 'Markdown' object has no attribute 'renderer'. Did you mean: 'render'?
```

How can I get marko to use the MarkdownRenderer with `.render()`? Or am I tackling this from the wrong side alltogether?

By the way: I am using version 1.3.0 of marko.

**Comment by frostming** [comment]
Just parse and render in the same go:

```python
import marko
from marko.md_renderer import MarkdownRenderer

markdown = marko.Markdown(renderer=MarkdownRenderer)
md_source = markdown.convert(md_text)
```
