### ISSUE TITLE
Parser crashes on incomplete link

### ISSUE THREAD

**Issue by g0ne** [frostming/marko#82]
Hi, first of all thank you for developing this awesome Markdown library!

I've found a string which causes the parser to crash:
```md
[](
```
Tested with Python 3.8.5 and marko 1.0.1 from PyPI.

```python
>>> import marko
>>> marko.convert("[](")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/marko/__init__.py", line 136, in convert
    return _markdown.convert(text)
  File "/usr/local/lib/python3.8/dist-packages/marko/__init__.py", line 103, in convert
    return self.render(self.parse(text))
  File "/usr/local/lib/python3.8/dist-packages/marko/__init__.py", line 114, in parse
    return self.parser.parse(text)
  File "/usr/local/lib/python3.8/dist-packages/marko/parser.py", line 70, in parse
    return self.block_elements["Document"](source_or_text)  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/marko/block.py", line 90, in __init__
    self.parse_inline()
  File "/usr/local/lib/python3.8/dist-packages/marko/block.py", line 72, in parse_inline
    child.parse_inline()
  File "/usr/local/lib/python3.8/dist-packages/marko/block.py", line 68, in parse_inline
    self.children = parser.parse_inline(self.children)  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/marko/parser.py", line 99, in parse_inline
    return inline_parser.parse(
  File "/usr/local/lib/python3.8/dist-packages/marko/inline_parser.py", line 30, in parse
    for match in etype.find(text):
  File "/usr/local/lib/python3.8/dist-packages/marko/inline.py", line 107, in find
    return inline_parser.find_links_or_emphs(text, _root_node)  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/marko/inline_parser.py", line 168, in find_links_or_emphs
    node = look_for_image_or_link(text, delimiters, i, root_node, matches)
  File "/usr/local/lib/python3.8/dist-packages/marko/inline_parser.py", line 196, in look_for_image_or_link
    match = _expect_inline_link(text, close + 1) or _expect_reference_link(
  File "/usr/local/lib/python3.8/dist-packages/marko/inline_parser.py", line 236, in _expect_inline_link
    if text[i] == "<":
IndexError: string index out of range
```

**Comment by frostming** [comment]
Thank you for catching this, it was fixed on the master
