### ISSUE TITLE
`ASTRenderer` doesn't support links

### ISSUE THREAD

**Issue by jack1142** [frostming/marko#95]
Code:
```py
from marko import Markdown
from marko.ast_renderer import ASTRenderer
from marko.ext.gfm import GFM

markdown = Markdown(renderer=ASTRenderer, extensions=[GFM])

ast = markdown("http://github.com/jack1142")
```
Traceback:
```py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python38\lib\site-packages\marko\__init__.py", line 106, in __call__
    return self.convert(text)
  File "C:\Python38\lib\site-packages\marko\__init__.py", line 103, in convert
    return self.render(self.parse(text))
  File "C:\Python38\lib\site-packages\marko\__init__.py", line 123, in render
    return r.render(parsed)
  File "C:\Python38\lib\site-packages\marko\renderer.py", line 63, in render
    return render_func(element)
  File "C:\Python38\lib\site-packages\marko\ast_renderer.py", line 40, in render_children
    rv["children"] = self.render(rv["children"])
  File "C:\Python38\lib\site-packages\marko\renderer.py", line 63, in render
    return render_func(element)
  File "C:\Python38\lib\site-packages\marko\ast_renderer.py", line 35, in render_children
    return [self.render(e) for e in element]
  File "C:\Python38\lib\site-packages\marko\ast_renderer.py", line 35, in <listcomp>
    return [self.render(e) for e in element]
  File "C:\Python38\lib\site-packages\marko\renderer.py", line 63, in render
    return render_func(element)
  File "C:\Python38\lib\site-packages\marko\ext\gfm\__init__.py", line 33, in render_paragraph
    children = self.render_children(element)
  File "C:\Python38\lib\site-packages\marko\ast_renderer.py", line 40, in render_children
    rv["children"] = self.render(rv["children"])
  File "C:\Python38\lib\site-packages\marko\renderer.py", line 63, in render
    return render_func(element)
  File "C:\Python38\lib\site-packages\marko\ast_renderer.py", line 35, in render_children
    return [self.render(e) for e in element]
  File "C:\Python38\lib\site-packages\marko\ast_renderer.py", line 35, in <listcomp>
    return [self.render(e) for e in element]
  File "C:\Python38\lib\site-packages\marko\renderer.py", line 63, in render
    return render_func(element)
  File "C:\Python38\lib\site-packages\marko\ext\gfm\__init__.py", line 76, in render_url
    return self.render_link(element)
AttributeError: 'MarkdownRenderer' object has no attribute 'render_link'
```

**Comment by jack1142** [comment]
It seems that in general, `ASTRenderer` doesn't really support GFM, i.e.:
```py
from marko import Markdown
from marko.ast_renderer import ASTRenderer
from marko.ext.gfm import GFM

markdown = Markdown(renderer=ASTRenderer, extensions=[GFM])

ast = markdown("`some` *text* with a **bunch** of ~~formatting~~ #123")
print(ast)
```
results in:
```
{'link_ref_defs': {}, 'children': ['<p>{\'children\': [{\'children\': \'some\', \'element\': \'code_span\'}, {\'element\': \'raw_text\', \'children\': \' \', \'escape\': True}, {\'children\': [{\'element\': \'raw_text\', \'children\': \'text\', \'escape\': True}], \'element\': \'emphasis\'}, {\'element\': \'raw_text\', \'children\': \' with a \', \'escape\': True}, {\'children\': [{\'element\': \'raw_text\', \'children\': \'bunch\', \'escape\': True}], \'element\': \'strong_emphasis\'}, {\'element\': \'raw_text\', \'children\': \' of \', \'escape\': True}, "<del>{\'children\': [{\'element\': \'raw_text\', \'children\': \'formatting\', \'escape\': True}], \'element\': \'strikethrough\'}</del>", {\'element\': \'raw_text\', \'children\': \' #123\', \'escape\': True}], \'element\': \'paragraph\'}</p>\n'], 'element': 'document'}
```

While:
```
from marko import Markdown
from marko.ast_renderer import ASTRenderer

markdown = Markdown(renderer=ASTRenderer)

ast = markdown("`some` *text* with a **bunch** of ~~formatting~~ #123")
print(ast)
```
Results in a more logical:
```
{'link_ref_defs': {}, 'children': [{'children': [{'children': 'some', 'element': 'code_span'}, {'element': 'raw_text', 'children': ' ', 'escape': True}, {'children': [{'element': 'raw_text', 'children': 'text', 'escape': True}], 'element': 'emphasis'}, {'element': 'raw_text', 'children': ' with a ', 'escape': True}, {'children': [{'element': 'raw_text', 'children': 'bunch', 'escape': True}], 'element': 'strong_emphasis'}, {'element': 'raw_text', 'children': ' of ~~formatting~~ #123', 'escape': True}], 'element': 'paragraph'}], 'element': 'document'}
```

**Comment by paxsali** [comment]
The mentioned "json"...

```json
{'link_ref_defs': {}, 'children': [{'children': [{'children': 'some', 'element': 'code_span'}, {'element': 'raw_text', 'children': ' ', 'escape': True}, {'children': [{'element': 'raw_text', 'children': 'text', 'escape': True}], 'element': 'emphasis'}, {'element': 'raw_text', 'children': ' with a ', 'escape': True}, {'children': [{'element': 'raw_text', 'children': 'bunch', 'escape': True}], 'element': 'strong_emphasis'}, {'element': 'raw_text', 'children': ' of ~~formatting~~ #123', 'escape': True}], 'element': 'paragraph'}], 'element': 'document'}
```

When given `jq` for parsing...

```bash
jq . more-logical.json
```

...results in this error:

```text
parse error: Invalid numeric literal at line 1, column 17
```

I also tried different online JSON parserer, they all say it isn't valid JSON.

**Comment by frostming** [comment]
It is a JSONable object, apparently not JSON string. It is a Python dict that is easy to operate with. @paxsali

**Comment by paxsali** [comment]
> It is a JSONable object, apparently not JSON string. It is a Python dict that is easy to operate with. @paxsali

Ok, now I understand. But is it really _wise_ to output "non-JSON" to the terminal on a commandline program?

I was using:

```bash
marko -r marko.ast_renderer.ASTRenderer 'roswell.md'
```

Any normal user will think the output is real JSON. It's **highly unintuitive** to work with an actual python representation on a CLI tool like this.

If the `marko` CLI tool didn't exist separately, I'd assume you have only the library to work with and must implement your own python programs, so then it would be "logical" that some internal functionality may return a python-only representation of an object inside a python only library. That would be acceptable and make sense.

But please, ... the `marko` CLI  tool **must** output true JSON! Or to the **very least**: explicitly mention in the usage/help dialog that it doesn't!

The way that it works right now is **highly unintuitive**.

This was my temporary workaround for the moment:

`marko_json.py`:

```python
import json
from marko import Markdown
from marko.ast_renderer import ASTRenderer

markdown = Markdown(renderer=ASTRenderer)

with open('roswell.md') as f:
    ast = markdown(f.read())

print(json.dumps(ast))

```

Now I can output JSON using...:

```bash
./marko_json.py | jq empty
echo $?
# 0
```

`jq` confirms it's valid JSON now.

There are many ways to go forward with this:

1. you could provide a generalized wrapper of above python code `marko_json` that accepts the exact same options as `marko`, but outputs JSON when ASTRenderer is chosen. it would be shipped alongside your `marko` binary.
2. you could provide a generic "python2json" converter CLI tool that's shipped alongside the `marko` CLI tool on installation, that can be used manually by the user in a pipe after `marko`, like this: `$ marko -r marko.ast_renderer.ASTRenderer ... | py2json`
3. you could extend the current `marko` CLI tool with a new option/switch `-j, --json` and support explicit JSON output when ASTRenderer is chosen.
4. you could simply hard-change the output of `marko` to JSON when ASTRenderer is chosen (and possibly break any existing code of your users who rely on it, however likely/unlike it may be).

My two cents and that's for your clarification. (also happy new year everyone)
